[package]
name = "mdb"
version = "0.1.0"
authors = ["Виталий Артемьев <vitaly.artemiev@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
dotenv = "0.15"
#postgres = "0.19"
actix-web = "3.3"
